apiVersion: v1
kind: Service
metadata:
  name: react-test-service
spec:
  selector:
    app: react-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Change to LoadBalancer if deploying to a cloud provider
