name: CI/CD Deploy to ArgoCD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME1 }}
          password: ${{ secrets.DOCKERHUB_TOKEN1 }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: elgbourisaad/react-test:latest1

      - name: Update image in deployment.yaml
        run: |
          sed -i 's|image: .*|image: elgbourisaad/react-test:latest1|' manifests/deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add manifests/deployment.yaml
          git commit -m "CI/CD: update image to latest"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
