name: CI/CD Deploy to ArgoCD

on:
  push:
    branches:
      - saad  # or "deploy" or any branch you choose

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME1 }}
        password: ${{ secrets.DOCKERHUB_TOKEN1 }}

    - name: Build and Push Docker Image
      run: |
        docker build -t elgbourisaad/react-test:latest1 .
        docker push elgbourisaad/react-test:latest1

    - name: Update image in deployment.yaml
      run: |
        sed -i 's|image: .*|image: elgbourisaad/react-test:latest1|' manifests/deployment.yaml
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add manifests/deployment.yaml
        git commit -m "CI/CD: update image to latest"
        git push

permissions:
  contents: write
